data:
  image: busybox
  container_name: lamp-dev-data
  volumes: ["/var/www/html", "/var/lib/mysql"]
  entrypoint: /bin/sh -c "echo 'Setup Data Container'"
mysql:
  image: webunitydesign/docker-compose-mysql
  container_name: lamp-dev-mysql
  volumes_from: ["data"]
app:
  image: webunitydesign/docker-compose-apache
  container_name: lamp-dev-app
  volumes_from: ["data"]
  ports: ["80:80"] # Port Exposure
  links: ["mysql:lamp-dev-mysql"]  # Use as a DB hostname if required
