data:
  image: debian
  container_name: lamp-dev-data
  volumes: ["/var/www/html", "/var/lib/mysql"]
  command: /bin/bash -c "echo 'Data Container' && while true; do sleep infinity; done"
mysql:
  image: webunitydesign/docker-compose-mysql
  container_name: lamp-dev-mysql
  volumes_from: ["data"]
app:
  image: webunitydesign/docker-compose-apache
  container_name: lamp-dev-app
  volumes_from: ["data"]
  ports: ["80:80"] # Port Exposure
  links: ["mysql:lamp-dev-mysql"]  # Use as a DB hostname if required
